send_message:
  name: Send WhatsApp Message
  description: Send a WhatsApp message via WAHA
  fields:
    phone_number:
      name: Phone Number
      description: Phone number in international format (e.g., +972541234567) or select from configured numbers
      required: true
      selector:
        text:
          type: tel
    message:
      name: Message
      description: Message text to send
      required: true
      selector:
        text:
          multiline: true 